<?php
// seed-data.php — defines $DATA grouped by Area (Snowmass Bike Park trails will be auto-excluded in the main seeder)

$DATA = [
  'Aspen' => [
    ['Rio Grande Trail', 43.5, 'Easy', 'N/S', 'Long, flat multi-use path along the river; ideal for beginners and connections.'],
    ['Butterline*', 1.2, 'Easy', 'N/S', 'Gentle introductory singletrack with smooth flow near Aspen core.'],
    ['Hunter Valley North*', 0.9, 'Easy', 'N/S', 'Easy access trail through meadows; great for warm-ups.'],
    ['Sunnyside Trail', 5.0, 'Intermediate', '+800 / -800', 'Flowy singletrack with moderate climbs and berms; accesses Aspen Mountain.'],
    ['Sky Mountain Park Loop', 6.0, 'Intermediate', '+1,000 / -1,000', 'Rolling network with techy roots; all-day loops near town.'],
    ['Maroon Creek Trail', 7.0, 'Intermediate', '+1,200 / -1,200', 'Scenic climb to Maroon Bells; dirt road to singletrack mix.'],
    ['Hobbit Trail*', 1.6, 'Intermediate', 'N/S', 'Fun, forested connector with mild ups and downs.'],
    ['Secret-Jedi Trail*', 0.9, 'Intermediate', 'N/S', 'Hidden gem singletrack with playful features and valley views.'],
    ['Hunter Creek (Overlook) Trail*', 0.8, 'Intermediate', 'N/S', 'Short overlook loop with creek-side riding and panoramas.'],
    ['Incline Trail*', 2.2, 'Easy/Intermediate', 'N/S', 'Gradual incline through aspen groves; versatile for building skills.'],
    ['Skyline Ridge Trail*', 2.3, 'Intermediate', 'N/S', 'Ridge-top flow with open meadows; connects to Snowmass.'],
    ['Government Trail', 8.0, 'Difficult', '+2,000 / -2,000', 'Steep, exposed rocky descent; expert-only.'],
    ['Hunter Valley Loop', 9.0, 'Difficult', '+1,500 / -1,500', 'Technical switchbacks and creek crossings; wildflower rewards.'],
    ['Shadyside Trail*', 2.6, 'Difficult', 'N/S', 'Steep, shaded tech descent with roots and rocks.'],
    ['East Rim Trail*', 1.2, 'Difficult', 'N/S', 'Exposed rim ride with big views and committing lines.'],
    ['Power of Four (full course)', 18.0, 'Black Diamond', '+8,389 / -8,389', 'Epic enduro vert fest; high-alpine combos.'],
    ['Cozyline', 4.0, 'Black Diamond', '+1,000 / -1,200', 'Gnarly freeride with jumps and steeps.'],
    ['Viewline', 3.5, 'Black Diamond', '+900 / -1,100', 'High-speed berms connecting to airlines.'],
  ],

  'Snowmass' => [
    ['Elk Camp Connector', 0.5, 'Easy', '+50 / -50', 'Short gondola access; beginner warm-up.'],
    ['Fanny Hill', 1.2, 'Easy', '+200 / -200', 'Gentle downhill flow with rollers.'],
    ['Kar', 1.5, 'Intermediate', '+400 / -400', 'Overgrown climber with mild tech.'],
    ['Ditch', 1.0, 'Intermediate', '+300 / -300', 'Versatile multi-use with flow.'],
    ['Rim Trail', 2.0, 'Intermediate', '+500 / -500', 'Panoramic bench-cut singletrack.'],
    ['Tom Blake*', 4.1, 'Intermediate', 'N/S', 'Classic loamy descent; park staple.'],
    ['Viking*', 2.5, 'Intermediate', 'N/S', 'Flowy intermediate with Nordic vibes and berms.'],
    ['Verde*', 4.2, 'Easy/Intermediate', 'N/S', 'Green valley connector; scenic and smooth.'],
    ['Vapor Trail*', 3.4, 'Intermediate/Difficult', 'N/S', 'Misty, techy flow with root sections.'],
    ['Valkyrie*', 0.9, 'Intermediate', 'N/S', 'Mythic-themed singletrack with switchbacks.'],
    ['Discovery Trail*', 2.0, 'Easy/Intermediate', 'N/S', 'Exploratory path for new riders; links zones.'],
    ['Viewline Trail*', 1.9, 'Intermediate', 'N/S', 'Vista-rich flow trail with open lines.'],
    ['Deadline Trail*', 1.6, 'Intermediate/Difficult', 'N/S', 'Time-trial style with punchy climbs.'],
    ['Deadline', 2.5, 'Black', '+600 / -800', 'Rooty drops; park favorite.'],
    ['Tom Blake', 3.0, 'Black', '+700 / -900', 'Steep freeride loam.'],
    ['Gonzo', 1.8, 'Black Diamond', '+600 / -1,000', 'Big-air freeride beast.'],
    ['Battle Axe', 2.0, 'Black Diamond', '+700 / -1,100', 'Jumps and gaps; pro-only.'],
    ['Valhalla', 1.7, 'Black Diamond', '+550 / -900', 'Tech rocks with epic vistas.'],
    ['Seven Star', 2.2, 'Black Diamond', '+800 / -1,200', 'Ultra-steep navigation challenge.'],
    ['Battle Axe*', 1.0, 'Difficult', 'N/S', 'Axe-themed gravity line with features.'],
    ['Animal Crackers*', 1.2, 'Difficult', 'N/S', 'Wild, playful tech descent.'],
  ],

  'The Crown' => [
    ['Overie', 2.5, 'Easy', '+300 / -300', 'Gentle loop with valley overlooks.'],
    ['Prince Creek Trail*', 1.8, 'Easy/Intermediate', 'N/S', 'Creek-side connector; approachable flow.'],
    ['Crown Royale', 3.0, 'Intermediate', '+400 / -600', 'Bermed flow descent; super fun.'],
    ['Undie (Lower)', 2.0, 'Intermediate', '+500 / -500', 'Ridge climb to FoG; balanced XC.'],
    ['Innie', 2.5, 'Intermediate', '+600 / -600', 'Switchback uphill to descents.'],
    ['Father of Ginormous (FoG)', 1.5, 'Intermediate', '+300 / -400', 'Approachable tech climber.'],
    ['Buzzard Basin', 4.0, 'Intermediate', '+700 / -700', 'Varied loop from Hay Park.'],
    ['Vasten Trail*', 6.1, 'Intermediate', 'N/S', 'Long, scenic traverse with views of Sopris.'],
    ['Imperial Gardens*', 3.4, 'Intermediate', 'N/S', 'Flowy garden-like singletrack.'],
    ['Buck Down*', 0.8, 'Intermediate/Difficult', 'N/S', 'Punchy connector with mild tech.'],
    ['North Porcupine*', 3.4, 'Intermediate', 'N/S', 'Porcupine-inspired ridge flow.'],
    ['Undie*', 5.5, 'Intermediate', 'N/S', 'Extended undulating singletrack.'],
    ['Buckhorn*', 4.6, 'Intermediate', 'N/S', 'Horned ridge with berms.'],
    ['BLM Road 8320*', 7.2, 'Intermediate', 'N/S', 'Graded road access to singletrack.'],
    ['Buckhorn Traverse*', 4.4, 'Intermediate', 'N/S', 'Cross-valley link with flow.'],
    ['Crown Tour Loop', 11.0, 'Difficult', '+1,581 / -1,581', 'Epic loop with Vasten downhill.'],
    ['Father of Ginormous*', 2.3, 'Difficult', 'N/S', 'Steep precursor to Ginormous.'],
    ['Ginormous', 3.5, 'Black Diamond', '+800 / -1,200', 'Slabby tech shred; video-famous.'],
  ],

  'Red Hill' => [
    ['Northside Access', 1.0, 'Easy', '+100 / -100', 'Gentle entry; seasonal closures.'],
    ['Lower Blue Ribbon', 2.0, 'Intermediate', '+400 / -400', 'Flowy climber/descent hybrid.'],
    ['Three Gulch', 1.1, 'Intermediate', '+300 / -300', 'Ridge traverse with views.'],
    ['Elk Traverse', 1.6, 'Intermediate', '+350 / -350', 'Mild tech connector to Roller Coaster.'],
    ['Northside Loop*', 5.1, 'Intermediate', 'N/S', 'Smooth-to-tech loop system.'],
    ['Faerie Trail*', 1.4, 'Intermediate', 'N/S', 'Whimsical varied terrain.'],
    ['Roller Coaster*', 0.2, 'Intermediate', 'N/S', 'Short dynamic ridgeline whoops.'],
    ['C-Line Trail*', 0.1, 'Intermediate', 'N/S', 'Quick flow bypass.'],
    ['Mushroom Rock', 1.5, 'Difficult', '+500 / -700', 'Rocky steep slab navigation.'],
    ['Blue Ribbon*', 2.0, 'Difficult', 'N/S', 'Rugged singletrack challenge.'],
    ['Three Gulch Trail*', 1.1, 'Difficult', 'N/S', 'Tough gulch terrain.'],
    ['Elk Traverse*', 1.6, 'Intermediate/Difficult', 'N/S', 'Blended challenge with views.'],
    ['B-Line*', 0.3, 'Difficult', 'N/S', 'Short skilled rider feature.'],
    ['Big Top Trail #82951*', 2.6, 'Intermediate/Difficult', 'N/S', 'Mixed riding circus.'],
    ['Lower Three Gulch*', 0.2, 'Intermediate/Difficult', 'N/S', 'Short gulch connector.'],
    ['Faerie', 1.2, 'Black Diamond', '+400 / -600', 'Steep precise lines.'],
    ['Red Hill Loop (full)', 5.0, 'Black Diamond', '+800 / -800', 'Techy sandstone heaven.'],
  ],

  'Glenwood Springs' => [
    ['Glenwood Canyon Rec Path', 18.0, 'Easy', '+200 / -200', 'Paved riverside scenic cruiser.'],
    ['Boy Scout Trail', 2.0, 'Easy', '+300 / -300', 'Gentle forest family path.'],
    ['Forest Hollow', 5.6, 'Intermediate', '+800 / -800', 'Rolling creek-shaded climbs.'],
    ['Lightning Bug', 1.6, 'Intermediate', '+400 / -500', 'Fun flow with mild tech. (+55 noted)'],
    ['Defiance', 3.0, 'Intermediate', '+600 / -600', 'Berms and roots; entertaining. (+23 noted)'],
    ['Grandstaff', 4.0, 'Intermediate', '+700 / -700', 'Rocky tech potential; high traffic. (+80 noted)'],
    ['Forest Hollow Trail*', 5.6, 'Intermediate', '+20 / N/S', 'Scenic intermediate loop.'],
    ['Tramway Trail* [South Canyon]', 3.2, 'Easy/Intermediate', '+35 / N/S', 'Varying skill access descent.'],
    ['Red Mountain Jeanne', 3.4, 'Difficult', '+900 / -900', 'Steep switchbacks; canyon views. (+26 noted)'],
    ['Wulfsohn', 2.5, 'Difficult', '+500 / -700', 'Flowy mud-prone repairs.'],
    ['Spring Valley Summit', 6.0, 'Difficult', '+1,200 / -1,200', 'High-altitude wildlife climb.'],
    ['Scout Trail* [South Canyon]', 2.5, 'Difficult', '+23 / N/S', 'Experienced rider challenge.'],
    ['Tramway', 3.2, 'Black Diamond', '+800 / -1,000', 'Overgrown tech; clippers needed.'],
    ['Alpine Slide', 2.0, 'Black Diamond', '+600 / -800', 'Fast slabs; critiqued build.'],
    ['Coal Camp Trail* [South Canyon]', 3.1, 'Intermediate/Difficult', '+30 / N/S', 'Muddy challenging loops.'],
    ['Lower Coal Camp Descent* [South Canyon]', 0.4, 'Intermediate', '+18 / N/S', 'Short fun descent.'],
    ['Alpine Slide Descent* [South Canyon]', 0.7, 'Difficult', '+2 / N/S', 'Quick difficult drop.'],
    ['Red Mountain Jeanne Golay Trail*', 3.4, 'Intermediate', '+26 / N/S', 'Named intermediate with flow.'],
    ['Defiance Trail*', 1.4, 'Intermediate/Difficult', '+23 / N/S', 'Varied challenge ride.'],
  ],

  'New Castle' => [
    ['Colorow Trail', 3.0, 'Easy', '+200 / -200', 'Looping BLM singletrack.'],
    ['Rio Grande Trail East', 5.0, 'Easy', '+100 / -100', 'Flat paved valley connector.'],
    ['Colorowflow: Goose*', 0.4, 'Easy/Intermediate', 'N/S', 'Gentle flow intro.'],
    ['Back To School*', 0.8, 'Easy/Intermediate', 'N/S', 'Approachable schoolyard loop.'],
    ['Faye\'s Fury', 1.6, 'Intermediate', '+400 / -400', 'Local flow favorite.'],
    ['Lookout Trail', 0.9, 'Intermediate', '+300 / -300', 'Vista climb out-and-back.'],
    ['Ward Peak', 4.0, 'Intermediate', '+800 / -800', 'Aspen-lined 8-mi loop part.'],
    ['Colorowflow: Maverick*', 0.4, 'Intermediate', 'N/S', 'Maverick flow section.'],
    ['Faye\'s Fury*', 1.6, 'Intermediate', 'N/S', 'Fury of flow and tech.'],
    ['Lookout Trail*', 0.9, 'Intermediate', 'N/S', 'Lookout with panoramas.'],
    ['Sallee Key Flow*', 0.4, 'Intermediate', 'N/S', 'Key flow trail.'],
    ['Main Elk Trail', 6.0, 'Difficult', '+1,500 / -1,500', 'Steep rooty XC.'],
    ['Burning Mountain', 5.0, 'Difficult', '+1,000 / -1,000', 'Built climber with warnings.'],
    ['Stairway to Heaven*', 2.0, 'Intermediate/Difficult', 'N/S', 'Heavenly steep switchbacks.'],
    ['Talbott\'s Burning Mountain Trail*', 3.6, 'Intermediate/Difficult', 'N/S', 'Burning tech ascent.'],
    ['Clark Ridge', 2.5, 'Black Diamond', '+700 / -700', 'Heinous cow path.'],
    ['Grand Hogback', 7.0, 'Black Diamond', '+1,200 / -1,200', 'Exposed slab ridge.'],
    ['Fire In The Mountain*', 2.6, 'Very Difficult', 'N/S', 'Fiery challenging descent.'],
    ['Oso\'s DH*', 0.5, 'Very Difficult', 'N/S', 'Bear-themed downhill gnar.'],
  ],
];